# Uncomment the next line to define a global platform for your project



platform :ios, '9.0'


target 'NewDemo' do

  project 'NewDemo'
  
  use_frameworks!

  pod 'SDWebImage'
  pod 'Masonry', '~> 1.1.0'
  pod 'TZImagePickerController'
  pod 'AFNetworking/Reachability'
  pod 'MJRefresh', '~> 3.6.1'
  pod 'MoorV7SDK', '~> 1.5.0'

  
end

