# Uncomment the next line to define a global platform for your project


platform :ios, '9.0'

target 'NewDemo' do

  project 'NewDemo'
  
  use_frameworks!

  pod 'SDWebImage', '~> 5.12.5'
  pod 'Masonry', '~> 1.1.0'
  pod 'TZImagePickerController'
  pod 'AFNetworking/Reachability'
  pod 'MJRefresh', '~> 3.6.1'
  pod 'MoorV7SDK', '~> 1.6.2'

  
end

